// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UwvLlm.Infrastructure.Data.Entities;

#nullable disable

namespace UwvLlm.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UwvLlm.Infrastructure.Data.Entities.MailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AutoResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("MailMessages");
                });

            modelBuilder.Entity("UwvLlm.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UwvLlm.Infrastructure.Data.Entities.UserNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExternalType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuickOptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Ip<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ChangePasswordAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ChangePasswordLockedOutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ForgetPasswordAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ForgetPasswordLockedOutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LoginLockedOutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RegisterCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RegisterLockedOutDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Ips", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Route<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("RouteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Session<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIp<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IpId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IpId");

                    b.HasIndex("UserId");

                    b.ToTable("UserIps", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSession<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIpId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserIpId");

                    b.ToTable("UserIpSessions", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionToken<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIpSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserIpSessionId");

                    b.ToTable("UserIpSessionTokens", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRoute<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIpSessionTokenId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserIpSessionTokenId");

                    b.ToTable("UserIpSessionTokenRoutes", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRouteRequest<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<byte>("Day")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Hour")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<long>("UserIpSessionTokenRouteId")
                        .HasColumnType("bigint");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("UserIpSessionTokenRouteId");

                    b.ToTable("UserIpSessionTokenRouteRequests", (string)null);
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserToken<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("UwvLlm.Infrastructure.Data.Entities.MailMessage", b =>
                {
                    b.HasOne("UwvLlm.Infrastructure.Data.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UwvLlm.Infrastructure.Data.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("UwvLlm.Infrastructure.Data.Entities.UserNotification", b =>
                {
                    b.HasOne("UwvLlm.Infrastructure.Data.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIp<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.Ip<UwvLlm.Infrastructure.Data.Entities.User>", "Ip")
                        .WithMany("UserIps")
                        .HasForeignKey("IpId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UwvLlm.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Ip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSession<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.Session<UwvLlm.Infrastructure.Data.Entities.User>", "Session")
                        .WithMany("UserIpSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("gAPI.Core.Server.Entities.UserIp<UwvLlm.Infrastructure.Data.Entities.User>", "UserIp")
                        .WithMany("UserIpSessions")
                        .HasForeignKey("UserIpId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("UserIp");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionToken<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.UserToken<UwvLlm.Infrastructure.Data.Entities.User>", "Token")
                        .WithMany("UserIpSessionTokens")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("gAPI.Core.Server.Entities.UserIpSession<UwvLlm.Infrastructure.Data.Entities.User>", "UserIpSession")
                        .WithMany("UserIpSessionTokens")
                        .HasForeignKey("UserIpSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("UserIpSession");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRoute<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.Route<UwvLlm.Infrastructure.Data.Entities.User>", "Route")
                        .WithMany("UserIpSessionTokenRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("gAPI.Core.Server.Entities.UserIpSessionToken<UwvLlm.Infrastructure.Data.Entities.User>", "UserIpSessionToken")
                        .WithMany("UserIpSessionTokenRoutes")
                        .HasForeignKey("UserIpSessionTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("UserIpSessionToken");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRouteRequest<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.HasOne("gAPI.Core.Server.Entities.UserIpSessionTokenRoute<UwvLlm.Infrastructure.Data.Entities.User>", "UserIpSessionTokenRoute")
                        .WithMany("UserIpSessionTokenRouteRequests")
                        .HasForeignKey("UserIpSessionTokenRouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserIpSessionTokenRoute");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserToken<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.HasOne("UwvLlm.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UwvLlm.Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Ip<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Navigation("UserIps");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Route<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokenRoutes");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.Session<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessions");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIp<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessions");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSession<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokens");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionToken<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokenRoutes");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserIpSessionTokenRoute<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokenRouteRequests");
                });

            modelBuilder.Entity("gAPI.Core.Server.Entities.UserToken<UwvLlm.Infrastructure.Data.Entities.User>", b =>
                {
                    b.Navigation("UserIpSessionTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
